### ISSUE TITLE
Pycryptodome doesn't work with paramiko so fabric doesn't work as well

### ISSUE THREAD

**Issue by mociepka** [mirumee/django-payments#100]
We start using it because of windows. Can we check OS as long as https://github.com/Legrandin/pycryptodome/issues/6 exists? If windows we will use `pycryptodome` otherwise we use `pycrypto`?

**Comment by patrys** [comment]
I'd rather fix paramiko. We don't use it in django-payments so working around it here does not seem to be the cleanest solution.
