### ISSUE TITLE
How to integrate coupons?

### ISSUE THREAD

**Issue by illing2005** [mirumee/django-payments#106]
Is there already a possibility to add lets say a 10% coupon to the payment?

Lets say the user has to pay 100 USD, but he has a 10% coupon. 
Now I want that he has to pay only 90 USD, but in the database the full amount should be saved.
Is something like this already integrated or should I extend the payment model to achieve this?

**Comment by patrys** [comment]
I would create two payment backends and create two payment objects, one for the coupon and one for the remaining amount.
