### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by agelinas** [mirumee/django-payments#107]
I tried installing django-payment from PyCharm and the command line. The installation fails. Will clone instead. Just thought that there might be a problem, but am not sure.

**Comment by artursmet** [comment]
Could you paste installation output from console?
Maybe you don't have requried development headers for some libraries.

**Comment by agelinas** [comment]
Hi,

Here is some of the output. I hope it is what you require.

Thank you for helping out. 

Downloading/unpacking cryptography
 Running setup.py (path:/home/alain/django/venv/django_env/build/cryptography/setup.py) egg_info for package cryptography

no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna>=2.0 (from cryptography)
Downloading/unpacking pyasn1>=0.1.8 (from cryptography)
Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /home/alain/django/venv/django_env/lib/python3.4/site-packages (from cr$
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /home/alain/django/venv/django_env/lib/python3.4/site-packages/set$
Downloading/unpacking cffi>=1.4.1 (from cryptography)
Running setup.py (path:/home/alain/django/venv/django_env/build/cffi/setup.py) egg_info for package cffi
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found

**Comment by artursmet** [comment]
As the error says: `No package 'libffi' found` . So you have to install libffi in your system (installation method depends on your platform). Here is an example for Fedora: http://forums.fedoraforum.org/showthread.php?t=297730
This issue is not related to django-payments itself. So I'll close it for now. But feel free to reopen it if you discover any problems with our package.
