### ISSUE TITLE
Incorrect saving of token

### ISSUE THREAD

**Issue by fredd4** [mirumee/django-payments#110]
Tokens in model are not saved with hyphens, what causes error in templates:

Reverse for 'process_payment' with arguments '()' and keyword arguments '{u'token': '27bf89af6dce40c7890a5c9f75b0b64e'}' not found. 1 pattern(s) tried: [u'payments/process/(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})/$']

Function 'hex' is used, but should be __str__ to have correct token format.

```
>>> uuid4().hex
'28a723ffa39843d0a739122563757abe'

>>> str(uuid4())
'fbbf843a-1acd-40f0-967e-97074a365075'

```

**Comment by patrys** [comment]
Looks like it was broken by dad351666a61bdb94fe4d6b610d08f579ec0d3c6
