### ISSUE TITLE
Remove name attrs on fields for StripeCardProvider

### ISSUE THREAD

**Issue by Asday** [mirumee/django-payments#118]
The name attrs present on the fields mean those inputs are submitted to the server, which means the server owner needs to have PCI compliance, the exact problem the stripe.js library is trying to avoid.

In `payments/static/js/payments/stripe.js`, the following lines:

```
        name: this.elements['name'].value,
        number: this.elements['number'].value,
        cvc: this.elements['cvv2'].value,
        exp_month: this.elements['expiration_0'].value,
        exp_year: this.elements['expiration_1'].value,
```

Simply need changing to

```
        name: this.elements.id_name.value,
        number: this.elements.id_number.value,
        cvc: this.elements.id_cvv2.value,
        exp_month: this.elements.id_expiration_0.value,
        exp_year: this.elements.id_expiration_1.value,
```

And the input widgets for those elements in django need their render method overriding to remove the `name=...` from the HTML.

**Comment by Asday** [comment]
Also, when doing so, the form doesn't validate, even though it doesn't need those details, so a custom `.clean` method for `payments.stripe.forms.PaymentForm` will need to read something like:

    if self.is_bound and self.cleaned_data.get('stripeToken', None) is not None:
        self.errors.pop('number', None)
        self.errors.pop('expiration', None)
        self.errors.pop('name', None)
        self.errors.pop('cvv2', None)

    return super(PaymentForm, self).clean()

**Comment by patrys** [comment]
I don't think the backend logic should know about these fields at all. It should only care about the token.

**Comment by Asday** [comment]
It should only care about the token, true, but it has to make exceptions for the fields that need to be omitted.  If one just omits the names from the html, the javascript breaks.  If one omits the names from the html and modifies the javascript to go by IDs instead, the django form breaks.

I wonder if there would be a way to make the fields not required on the form, seeing as Stripe.js takes care of that for us.  That would remove the need for the workaround detailed in https://github.com/mirumee/django-payments/issues/118#issuecomment-250723389

**Comment by patrys** [comment]
I think a custom form template (that has fields the Form does not know about) would solve it.

**Comment by Asday** [comment]
That's what I'm doing now, but I also have to monkeypatch the javascript, as it looks up those fields by their name, and monkeypatch the form validation, as it requires those fields.

It also means I lose the nice automatic building of the expiry date widget, and will have to update the selection of years as time goes on.

**Comment by pymarco** [comment]
We are starting a project that will use Stripe.js to avoid having PCI compliance. 

Am I correct in understanding that PCI compliance is required when using django-payments StripeCardProvider?

**Comment by Asday** [comment]
Unless you implement the workarounds I detailed, yes, as the payment details will touch your server.  The workarounds I detailed are relatively simple, and if you need to use more than one payment method, (for instance, including a PayPal option), this library with the workarounds is much less work than separate libraries for everything.

**Comment by pymarco** [comment]
Thank you @Asday. 

I have written a short tutorial for Saleor integration.
https://github.com/mirumee/saleor/issues/749#issuecomment-272230162

**Comment by Asday** [comment]
My eternal pleasure, @pymarco.  If Saleor is exactly like this, remember to manually render the form fields in HTML to remove the `name` attribute, otherwise the data will be sent to your server, bringing PCI compliance issues.
