### ISSUE TITLE
Django 1.11 incompatible calls to build_attrs()

### ISSUE THREAD

**Issue by amorphic** [mirumee/django-payments#144]
In Django 1.11 kwargs were removed from the definition of `Widget.build_attrs`. More information on this is [here](https://code.djangoproject.com/ticket/28095).

There are 3 places where `build_attrs` is used with kwargs in django-payments:

* `widgets.SensitiveTextInput`
* `stripe.widgets.StripeCheckoutWidget`
* `cybersource.forms.FingerprintWidget`

When using any of these with Django 1.11 an exception is thrown for the unexpected kwargs. __Thus all of these are completely broken under 1.11__.

The solution (as mentioned in the post above) seems to be to use something like `attrs.update(new_attrs_dict)`.

**Comment by patrys** [comment]
Paging @elwoodxblues 🚒

**Comment by amorphic** [comment]
@patrys @elwoodxblues thanks guys - this is a showstopper for us launching our new Saleor-powered web store using Stripe.

I'd fix it myself but I'm not 100% sure of the implications and I figure most of the work will be cutting a new release, which only you guys can do...

**Comment by amorphic** [comment]
@patrys @elwoodxblues I know you guys are probably really busy but is there any ETA for resolution on this? It's a showstopper for anybody using Stripe with Saleor. Would you prefer me to submit a PR?

**Comment by elwoodxblues** [comment]
Hi @amorphic, unfortunately I had no time yet to tackle this issue, although it's on my list for this week. But if you already have a solution for this then we would welcome a PR. We'll review it and release a new version as soon as possible.
