### ISSUE TITLE
Contributing a translation

### ISSUE THREAD

**Issue by ludwiktrammer** [mirumee/django-payments#163]
I'd like to contribute a Polish translation for the project. I can see that you import translations from transifex, but I don't know how to find the project there. Or should I do this by hand and just do a pull request?

**Comment by patrys** [comment]
The project is here: https://www.transifex.com/mirumee/django-payments/

Pozdrawiam 😄

**Comment by ludwiktrammer** [comment]
It's done :)

**Comment by patrys** [comment]
Thank you!
