### ISSUE TITLE
cybersource payment provider  doesn't work on windows development machine

### ISSUE THREAD

**Issue by inoks** [mirumee/django-payments#56]
URLError at /payments/process/cybersource/

<urlopen error [Error 3] : '\\xml\\CyberSourceTransaction_1.101.test.wsdl'>
Request Method:	GET
Request URL:	http://localhost/payments/process/cybersource/
Django Version:	1.7.1
Exception Type:	URLError
Exception Value:	
<urlopen error [Error 3] : '\\xml\\CyberSourceTransaction_1.101.test.wsdl'>
Exception Location:	C:\Python27\lib\urllib2.py in open_local_file, line 1357
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.8
Python Path:	
['d:\\Dropbox\\workspace\\dss\\src',
 'C:\\Python27\\lib\\site-packages\\mysql_python-1.2.4-py2.7-win32.egg',
 'd:\\dropbox\\workspace\\saleor',
 'C:\\Python27\\lib\\site-packages\\satchless-1.1.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\prices-0.5.1-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\google_measurement_protocol-0.1.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\fake_factory-0.4.2-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_selectable-0.8.0-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_prices-0.3.4-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_mptt-0.6.1-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_model_utils-2.0.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\django_images-0.4.1-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\babeldjango-0.2.2-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\babel-1.3-py2.7.egg',
 'C:\\Windows\\SYSTEM32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']
Server time:	Fri, 19 Dec 2014 14:55:52 +0000

**Comment by patrys** [comment]
@inoks this is now fixed, sorry for the long wait.

**Comment by inoks** [comment]
Thank!
Will definitely try it again in he next project!
