### ISSUE TITLE
PayPal Backend state

### ISSUE THREAD

**Issue by Henner** [mirumee/django-payments#65]
Hi, what state is the PayPal Backend in? I tried to figure out how to use it, but I think the implementation is too old! Today I need User, Pass and Signature (and maybe API Version) or even better I should use adaptive payments...

Am I wrong?

**Comment by patrys** [comment]
It's working fine. If you'd like to see particular features implemented, please open a separate issue for each.

**Comment by Henner** [comment]
OK. An what User do I have to pass in? My original PayPal User or the on created under tools => API Access?

**Comment by patrys** [comment]
Using credentials created in API Access is safer but it should also work with your email and password.

**Comment by Henner** [comment]
hmm, is there a mailing list?
what is PAYMENT_BASE_URL and whats the difference to PAYMENT_HOST?
PAYMENT_BASE_URL is only used in the docs...

**Comment by patrys** [comment]
Ouch! Please file a bug for this, it used to be called `PAYMENT_BASE_URL` but it's now two separate settings: `PAYMENT_HOST` and `PAYMENT_USES_SSL`. They are used to construct the callback URL to pass to the payment gateway.

**Comment by Henner** [comment]
OK, how does that affect `get_failure_url` and `get_success_url`? I tried 
```    
def get_failure_url(self):
        return '%s/tickets/payment_gateway/error/' % settings.PAYMENT_BASE_URL
```
and ended up in:
http://example.com/tickets/payment/gateway/process/cee2d187-f5b5-4a35-9be6-aa7a965af677/?token=EC-3Y741676R5341274R

by having set:
`PAYMENT_BASE_URL = 'http://192.168.33.17'`

and:
```
    url('^tickets/payment/gateway/', include('payments.urls')),                       
```

**Comment by Henner** [comment]
now I have:
```
    def get_failure_url(self):
        return '%s/tickets/payment_gateway/error/' % settings.PAYMENT_HOST
```

and:
```
PAYMENT_HOST = 'http://dev.tx.net'
PAYMENT_USES_SSL = False
```
where dev.tx.net points to a local IP.

But I get: 
Provided return url is invalid.

**Comment by Henner** [comment]
OK, no http for `PAYMENT_HOST`…
but I still end up in curious urls:
http://dev.tx.net/tickets/payment/gateway/process/12b5f6c1-be4f-442b-af2a-e6cbedff02f9/dev.tx.net/tickets/payment_gateway/error/

a mixture of `get_failure_url` and your payment urls.py magic...

**Comment by Henner** [comment]
can you remind me, why does payment not appear automatically in the admin interface? Why do I have to do in admin.py:
```
class PaymentAdmin(admin.ModelAdmin):
    pass

admin.site.register(Payment, PaymentAdmin)
```
if this is normal, you may add it to the docs...
