### ISSUE TITLE
Authorize.Net doesn't change captured amount.

### ISSUE THREAD

**Issue by 722C** [mirumee/django-payments#74]
https://github.com/mirumee/django-payments/issues/60 made it so that the transaction is posted up to Authorize.Net.  It does function, including setting the payment as "Confirmed" and placing the transaction into Authorize.Net's unsettled queue (which does properly settle whenever Authorize.Net runs settlements).  However, no amount is ever recorded as captured in the payment.

![screen shot 2015-06-02 at 2 11 38 pm](https://cloud.githubusercontent.com/assets/5333596/7945982/57e5556a-0931-11e5-8cc6-18aead767a71.png)

**Comment by patrys** [comment]
Whoever is going to fix that: we obviously need better tests for Authorize.net.

**Comment by bogdal** [comment]
Fixed in `0.7.0` version.
