### ISSUE TITLE
Braintree only works in sandbox mode

### ISSUE THREAD

**Issue by audioburn** [mirumee/django-payments#80]
__init__() got an unexpected keyword argument 'sandbox'

when I have 

    PAYMENT_VARIANTS = {
     'braintree': ('payments.braintree.BraintreeProvider', {
        'merchant_id': MERCHANT_ID,
        'public_key': PUBLIC_KEY,
        'private_key': PRIVATE_KEY,
        'sandbox': IS_SANDBOX
        })}

In my settings, works fine when I remove it, but only works in sandbox.

**Comment by bogdal** [comment]
@audioburn this was fixed in `0.7.0` version. Please make sure you have it.
