### ISSUE TITLE
Paypal Card Provider refund does not work

### ISSUE THREAD

**Issue by illing2005** [mirumee/django-payments#87]
I am getting this error message:

    File .../payments/models.py", line 171, in refund
    amount = provider.refund(amount)
    File ".../payments/paypal/__init__.py", line 295, in     refund
    url = self.links['refund']['href']
    KeyError: u'refund'

**Comment by patrys** [comment]
Has this payment been settled or only pre-authorized?

**Comment by illing2005** [comment]
Not sure what you mean with "settled".
The payment has the status "confirmed" and I am using `capture=True` in my settings.

**Comment by patrys** [comment]
Thanks, we will try to reproduce. Could you share anonymized contents of all the model fields? It could be a bug that was fixed in today's release.
