### ISSUE TITLE
Paypal authorization/capture - capture link

### ISSUE THREAD

**Issue by pgpgpg** [mirumee/django-payments#99]
When trying to capture a payment that has been authorized I am getting an error that is traced back to the _get_links method within the PaypalProvider class:

def _get_links(self, payment):
        extra_data = json.loads(payment.extra_data or '{}')
        links = extra_data.get('links', {})
        return links

In order for the capture links to be extracted from extra_data the following line is required to replace  links = extra_data.get('links', {}) :

links = extra_data['response']['transactions'][0]['related_resources'][0]['authorization']['links']

otherwise incorrect links are pulled and a PayPal error is raised.

**Comment by patrys** [comment]
@mociepka?

**Comment by patrys** [comment]
This seems to be the same bug as #87.

**Comment by bogdal** [comment]
@pgpgpg This problem was fixed. Please try the latest version of `django-payments`.
